logging:
  config: classpath:logback-product.xml
server:
  port: '8080'
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: root1
    url: jdbc:mysql://127.0.0.1:3306/starrysea?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: root
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  mail:
    host: smtp.starrysea.top
    password: Xingzhihai2017
    port: '465'
    properties:
      mail:
        smtp:
          auth: 'true'
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
            fallback: 'false'
            port: '465'
          timeout: '10000'
    username: mumuzhizhi@starrysea.top
  mvc:
    favicon:
      enabled: 'false'
  thymeleaf:
    mode: LEGACYHTML5
    servlet:
      content-type: text/html
  redis:
    host: 127.0.0.1
    port: 6379
    password: root1
    jedis:
      pool:
        max-active: 8
        max-wait: 1800
        max-idle: 8
        min-idle: 0
    timeout: 20000 
  devtools: 
    add-properties: false
  banner:
    charset: UTF-8
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    publisher-confirms: true
management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: shutdown
ss:
  fileroot: /usr/share/nginx/
payelves:
  gateway:  https://www.payelves.com/api/v1/pay/web
  openId: AWLg6Cj3d
  token:  8216e8aebcd143f590abf996f14e29fe
  uuid: yeah-Tiger
  clientVersion:  3.3.0
  appKey: 8067244293554179